zuul:
  prefix: /api
  routes:
    bus-service-client:
      path: /bus-service/**
      serviceId: bus-service-client
    train-service-client:
      path: /train-service/**
      serviceId: train-service-client

