server:
  port: 8888

management:
  context-path: /admin
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GreenMountainPower/spring-cloud-netflix-microservices
          search-paths: configs